# This is a basic workflow to help you get started with Actions

name: WRPP  # nome 


on:  # Controls when the action will run. 


  schedule:
    - cron: "0 23 * * 1" #// Every Monday at 1PM UTC (9AM EST)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1  #rmarkdown


      - name: install pkg #colocando um arquivo com os pacotes que usei no markdown 
        run: |
          Rscript install_packages.R  

      - name: render report #botao knitr
        run: |
          R -e 'rmarkdown::render("index.Rmd")'

      - name: Commit update 
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "atualizando relatorio"
          git push 
      
